/*
 * Generated by erpcgen 1.9.0 on Wed Jun  1 05:43:15 2022.
 *
 * AUTOGENERATED - DO NOT EDIT
 */


#if !defined(_BBCar_control_h_)
#define _BBCar_control_h_

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include "erpc_version.h"

#if 10900 != ERPC_VERSION_NUMBER
#error "The generated shim code version is different to the rest of eRPC code."
#endif

#if !defined(ERPC_TYPE_DEFINITIONS)
#define ERPC_TYPE_DEFINITIONS

#endif // ERPC_TYPE_DEFINITIONS

/*! @brief BBCarService identifiers */
enum _BBCarService_ids
{
    kBBCarService_service_id = 1,
    kBBCarService_Speed_id = 1,
    kBBCarService_distance_id = 2,
};

#if defined(__cplusplus)
extern "C" {
#endif

//! @name BBCarService
//@{
void Speed(void);

void distance(void);
//@}

#if defined(__cplusplus)
}
#endif

#endif // _BBCar_control_h_
